apiVersion: apps/v1
kind: Deployment
metadata:
  name: skincare-cv-app
  labels:
    app: skincare-cv-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skincare-cv-app
  template:
    metadata:
      labels:
        app: skincare-cv-app
    spec:
      initContainers:
        - name: migrations
          image: onepantsu/skincare-migrations:v1.0
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              value: postgres-service
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_PORT

      containers:
      - name: skincare-cv-app
        image: onepantsu/skincare-cv:v1.0-clip
        ports:
        - containerPort: 8080
        args:
          - "-p"
          - "8080"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3